### ISSUE TITLE
RocketMQ module can't run in GraalVM environment

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#3101]
**Which Component**
eg. RocketMQ

**Describe what problem you have encountered**
RocketMQ Client support run in GraalVM environment. it can't run now. You can reproduce this issue by following these steps：
Prerequisites Start RocketMQ broker and nameserver

1. Download the Spring Cloud Alibaba project, switch to the 2022.x branch, enter the `rocketmq-broadcast-producer-example` module, enter the pom.xml file, add below dependency and plugin.
 ```
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>fastjson</artifactId>
    <version>2.0.22</version>
</dependency>

<plugin>
  <groupId>org.graalvm.buildtools</groupId>
  <artifactId>native-maven-plugin</artifactId>
  <configuration>
    <classesDirectory>${project.build.outputDirectory}</classesDirectory>
    <metadataRepository>
      <enabled>true</enabled>
    </metadataRepository>
    <requiredVersion>22.3</requiredVersion>
    <buildArgs>
      --initialize-at-build-time=org.apache.commons.logging.LogFactoryService
    </buildArgs>
  </configuration>
  <executions>
    <execution>
      <id>add-reachability-metadata</id>
      <goals>
        <goal>add-reachability-metadata</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```
3. Execute `mvn clean -Pnative spring-boot:run`. After the application starts, it will scan the code dynamic properties. After about 10 seconds, stop the application through control+C, and there will be a `META-INF.native` in the resources directory. image directory, there will be a static configuration file corresponding to the dynamic properties of the code below. You need to enter the `reflect-config.json` file to delete the corresponding item of `org.springframework.integration.config.ConverterRegistrar$IntegrationConverterRegistration`.
4. Execute `mvn clean -Pnative native:compile` to build the native image. If it goes well, it will be built successfully, and then `target/rocketmq-broadcast-producer-example` should start the application and the problem should be reproduced.
   
  ```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:761) ~[rocketmq-broadcast-producer-example:3.0.0]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:748) ~[rocketmq-broadcast-producer-example:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[rocketmq-broadcast-producer-example:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[rocketmq-broadcast-producer-example:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[rocketmq-broadcast-producer-example:3.0.0]
        at com.alibaba.cloud.examples.broadcast.RocketMQBroadcastProducerApplication.main(RocketMQBroadcastProducerApplication.java:48) ~[rocketmq-broadcast-producer-example:na]
Caused by: org.springframework.messaging.MessagingException: null
        at com.alibaba.cloud.stream.binder.rocketmq.integration.outbound.RocketMQProducerMessageHandler.doFail(RocketMQProducerMessageHandler.java:272) ~[na:na]
        at com.alibaba.cloud.stream.binder.rocketmq.integration.outbound.RocketMQProducerMessageHandler.handleMessageInternal(RocketMQProducerMessageHandler.java:201) ~[na:na]
        at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:106) ~[rocketmq-broadcast-producer-example:na]
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:74) ~[rocketmq-broadcast-producer-example:na]
        at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:1118) ~[na:na]
        at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:106) ~[rocketmq-broadcast-producer-example:na]
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:74) ~[rocketmq-broadcast-producer-example:na]
        at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[rocketmq-broadcast-producer-example:6.0.0]
        at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[na:na]
        at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[na:na]
        at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[rocketmq-broadcast-producer-example:na]
        at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:368) ~[rocketmq-broadcast-producer-example:na]
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:322) ~[rocketmq-broadcast-producer-example:na]
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:292) ~[rocketmq-broadcast-producer-example:na]
        at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:177) ~[rocketmq-broadcast-producer-example:na]
        at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:143) ~[rocketmq-broadcast-producer-example:na]
        at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:139) ~[rocketmq-broadcast-producer-example:na]
        at com.alibaba.cloud.examples.broadcast.RocketMQBroadcastProducerApplication.lambda$producer$0(RocketMQBroadcastProducerApplication.java:60) ~[rocketmq-broadcast-producer-example:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:758) ~[rocketmq-broadcast-producer-example:3.0.0]
        ... 5 common frames omitted
Caused by: java.lang.IllegalStateException: org.apache.rocketmq.remoting.exception.RemotingSendRequestException: send request to <127.0.0.1:9876> failed
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:680) ~[rocketmq-broadcast-producer-example:4.9.4]
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:510) ~[rocketmq-broadcast-producer-example:4.9.4]
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.tryToFindTopicPublishInfo(DefaultMQProducerImpl.java:675) ~[rocketmq-broadcast-producer-example:4.9.4]
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:548) ~[rocketmq-broadcast-producer-example:4.9.4]
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1363) ~[rocketmq-broadcast-producer-example:4.9.4]
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1307) ~[rocketmq-broadcast-producer-example:4.9.4]
        at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:333) ~[rocketmq-broadcast-producer-example:4.9.4]
        at com.alibaba.cloud.stream.binder.rocketmq.integration.outbound.RocketMQProducerMessageHandler.send(RocketMQProducerMessageHandler.java:226) ~[na:na]
        at com.alibaba.cloud.stream.binder.rocketmq.integration.outbound.RocketMQProducerMessageHandler.handleMessageInternal(RocketMQProducerMessageHandler.java:183) ~[na:na]
        ... 22 common frames omitted
Caused by: org.apache.rocketmq.remoting.exception.RemotingSendRequestException: send request to <127.0.0.1:9876> failed
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:441) ~[rocketmq-broadcast-producer-example:4.9.4]
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:390) ~[na:na]
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1394) ~[na:na]
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1384) ~[na:na]
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:623) ~[rocketmq-broadcast-producer-example:4.9.4]
        ... 30 common frames omitted
```

**Comment by ralf0131** [comment]
I can reproduce this issue, and I've found out that  it's due to the incomplete reflect-config.json. Replacing the following content should make the example work:

```
{
  "name":"org.apache.rocketmq.remoting.protocol.RemotingCommand",
  "allDeclaredFields":true,
  "allDeclaredMethods":true,
  "allDeclaredConstructors":true
},
{
  "name":"org.apache.rocketmq.common.protocol.route.BrokerData",
  "allDeclaredFields":true,
  "allPublicMethods":true,
  "allPublicConstructors":true
},
{
  "name":"org.apache.rocketmq.common.protocol.route.TopicRouteData",
  "allDeclaredFields":true,
  "allPublicMethods":true,
  "allPublicConstructors":true
},
{
  "name":"org.apache.rocketmq.common.protocol.route.QueueData",
  "allDeclaredFields":true,
  "allPublicMethods":true,
  "allPublicConstructors":true
},
```

**Comment by ralf0131** [comment]
I've also managed to run the `rocketmq-broadcast-consumer1-example` , the following config in `reflect-config.json` should be replaced.

```
{
  "name":"org.apache.rocketmq.common.protocol.heartbeat.HeartbeatData",
  "allDeclaredFields":true,
  "allPublicMethods":true
},
{
  "name":"org.apache.rocketmq.common.protocol.heartbeat.ConsumerData",
  "allDeclaredFields":true,
  "allPublicMethods":true
},
{
  "name":"org.apache.rocketmq.common.protocol.heartbeat.ProducerData",
  "allDeclaredFields":true,
  "allPublicMethods":true
},
{
  "name":"org.apache.rocketmq.common.protocol.heartbeat.SubscriptionData",
  "allDeclaredFields":true,
  "allPublicMethods":true
},
```

**Comment by steverao** [comment]
The issue has been solved and close now.

**Comment by yuluo-yx** [comment]
I encounter the following problem when running example(I ran the spring-boot:run command for at least 10 seconds) :
```
[7/7] Creating image...
                                                                                  (0.0s @ 4.11GB)
Fatal error: com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.VMError$HostedError: New Method or Constructor found as reachable after static analysis: public ja
va.lang.Object org.springframework.integration.config.ConverterRegistrar$IntegrationConverterRegistration.converter()
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:696)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: com.oracle.svm.core.util.VMError$HostedError: New Method or Constructor found as reachable after static analysis: public java.lang.Object org.springframework.integration.c
onfig.ConverterRegistrar$IntegrationConverterRegistration.converter()
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionFeature.getOrCreateAccessor(ReflectionFeature.java:121)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.target.ExecutableAccessorComputer.transform(ExecutableAccessorComputer.java:43)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.ComputedValueField.computeValue(ComputedValueField.java:343)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:313)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:38)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:97)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.meta.HostedField.readValue(HostedField.java:161)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addObjectToImageHeap(NativeImageHeap.java:439)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addObject(NativeImageHeap.java:295)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.processAddObjectWorklist(NativeImageHeap.java:598)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addTrailingObjects(NativeImageHeap.java:198)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:678)
        ... 4 more
------------------------------------------------------------------------------------------------------------------------
                        19.8s (8.9% of total time) in 46 GCs | Peak RSS: 5.98GB | CPU load: 6.49
========================================================================================================================
Failed generating 'rocketmq-broadcast-producer-example' after 3m 41s.
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:07 min
[INFO] Finished at: 2023-06-29T22:08:32+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.19:compile (default-cli) on project rocketmq-broadcast-producer-example: Execution of C:\Users\14815\.sd
kman\candidates\java\current\bin\native-image.cmd @target\tmp\native-image-7864971393992100226.args returned non-zero result -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
You need to add the following configuration to this configuration item to compile normally:

```
"allPublicMethods":true,

{
  "name":"org.springframework.integration.config.ConverterRegistrar$IntegrationConverterRegistration",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "queryAllDeclaredConstructors":true,
  "methods":[{"name":"<init>","parameterTypes":["java.lang.Object"] }]
},
```

**Comment by imgoby** [comment]
the newest version has the same problem. Is it resolved?

    <spring.cloud.alibaba.version>2022.0.0.0</spring.cloud.alibaba.version>
        <spring.cloud.version>2022.0.0</spring.cloud.version>

**Comment by imgoby** [comment]
@steverao In the newest version 2022.0.0.0, This issue still exists. I have to add the same settting mentioned as above to the file: ${myprojectdir}\src\main\resources\META-INF\native-image\reflect-config.json


```
[
  {
    "name":"org.apache.rocketmq.remoting.protocol.RemotingCommand",
    "allDeclaredFields":true,
    "allDeclaredMethods":true,
    "allDeclaredConstructors":true
  },
  {
    "name":"org.apache.rocketmq.common.protocol.route.BrokerData",
    "allDeclaredFields":true,
    "allPublicMethods":true,
    "allPublicConstructors":true
  },
  {
    "name":"org.apache.rocketmq.common.protocol.route.TopicRouteData",
    "allDeclaredFields":true,
    "allPublicMethods":true,
    "allPublicConstructors":true
  },
  {
    "name":"org.apache.rocketmq.common.protocol.route.QueueData",
    "allDeclaredFields":true,
    "allPublicMethods":true,
    "allPublicConstructors":true
  }
]


```

**Comment by imgoby** [comment]
https://sca.aliyun.com/en/blog/rocketmq-adapt-graalvm/

**Comment by imgoby** [comment]
> the newest version has the same problem. Is it resolved?
> 
> ```
> <spring.cloud.alibaba.version>2022.0.0.0</spring.cloud.alibaba.version>
>     <spring.cloud.version>2022.0.0</spring.cloud.version>
> ```

yes. refer to: https://sca.aliyun.com/en/blog/rocketmq-adapt-graalvm/

(1)
reflect-config.json :
```

  {
    "name":"org.apache.rocketmq.remoting.protocol.RemotingCommand",
    "allDeclaredFields":true,
    "allDeclaredMethods":true,
    "allDeclaredConstructors":true
  },
  {
    "name":"org.apache.rocketmq.common.protocol.route.BrokerData",
    "allDeclaredFields":true,
    "allPublicMethods":true,
    "allPublicConstructors":true
  },
  {
    "name":"org.apache.rocketmq.common.protocol.route.TopicRouteData",
    "allDeclaredFields":true,
    "allPublicMethods":true,
    "allPublicConstructors":true
  },
  {
    "name":"org.apache.rocketmq.common.protocol.route.QueueData",
    "allDeclaredFields":true,
    "allPublicMethods":true,
    "allPublicConstructors":true
  },

  {
    "name":"org.apache.rocketmq.common.protocol.body.TopicList",
    "allDeclaredFields":true,
    "allPublicMethods":true,
    "allPublicConstructors":true
  },
  {
    "name":"org.apache.rocketmq.common.protocol.route.QueueData",
    "allDeclaredFields":true,
    "allPublicMethods":true,
    "allPublicConstructors":true
  },
  {
    "name":"org.apache.rocketmq.common.protocol.route.QueueData",
    "allDeclaredFields":true,
    "allPublicMethods":true,
    "allPublicConstructors":true
  },
  {
    "name":"org.apache.rocketmq.common.protocol.route.QueueData",
    "allDeclaredFields":true,
    "allPublicMethods":true,
    "allPublicConstructors":true
  },
  {
    "name":"org.apache.rocketmq.common.protocol.body.ClusterInfo",
    "allDeclaredFields":true,
    "allPublicMethods":true,
    "allPublicConstructors":true
  },
  {
    "name":"java.util.HashSet",
    "allDeclaredFields":true,
    "allPublicMethods":true,
    "allPublicConstructors":true
  }
```
